name: 'envirnment test'

on: 
  workflow_call:
# TODO add some inputs if you really need them, you example inputs could be removed without loss of information.

jobs:
  call-workflow-passing-dev:
    if: ${{ github.ref == 'refs/heads/dev' }}
    uses: sushmagoudar/El-base/.github/workflows/main.yml@dev
    secrets: inherit

  call-workflow-passing-test:
    if: ${{ github.ref == 'refs/heads/test' }}
    uses: sushmagoudar/El-base/.github/workflows/main.yml@test
    secrets: inherit

  call-workflow-passing-prod:
    if: ${{ github.ref == 'refs/heads/prod' }}
    uses: sushmagoudar/El-base/.github/workflows/main.yml@prod
    secrets: inherit



  
